### ISSUE TITLE
NameErrors when running RMINDO3 for Mac OS pyscf 2.0.1

### ISSUE THREAD

**Issue by JamesB-1qbit** [pyscf/semiempirical#1]
Steps to reproduce 
```
>>> import pyscf
>>> mol_h2o = pyscf.gto.M(atom = 'O 0 0 0; H 0 1 0; H 0 0 1', basis = 'ccpvdz')
>>> from pyscf.semiempirical import mindo3
>>> solver = mindo3.RMINDO3(mol_h2o)
>>> solver.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/lib/misc.py", line 512, in run
    self.kernel(*args)
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/lib/misc.py", line 631, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/scf/hf.py", line 1642, in scf
    self.dump_flags()
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/semiempirical/mindo3.py", line 173, in dump_flags
    log = logger.new_logger(mol, verbose)
NameError: name 'mol' is not defined
```

If you change `mol` in line 173 to `self.mol` or `self._mindo_mol`. I don't know which is correct, then it fails again at line 181
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/lib/misc.py", line 512, in run
    self.kernel(*args)
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/lib/misc.py", line 631, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/scf/hf.py", line 1642, in scf
    self.dump_flags()
  File "/Users/jamesbrown/Documents/Coding/environments/pyscftest/lib/python3.9/site-packages/pyscf/semiempirical/mindo3.py", line 181, in dump_flags
    return hf.RHF.dump_flags(self, log)
NameError: name 'hf' is not defined
```

Changing line 181
`return hf.RHF.dump_flags(self, log)` to `return scf.hf.RHF.dump_flags(self, log)` allows the calculation to finish.

```
converged SCF energy = -12.5424908345999
Heat of formation = -48.8262064549162 kcal/mol, -0.07780798779448 Eh
<pyscf.semiempirical.mindo3.RMINDO3 object at 0x10f6ffc40>

```

**Comment by fishjojo** [comment]
Fixed in 37044a022296d860c4feffb0415789fc8a66b660
